package app

import (
	"context"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

// The filter proxy is a local URL-filtering HTTP proxy (privoxy on this
// machine) that alpaca forwards to instead of reaching the internet directly.
//
// It only ever applies to contexts whose proxy_mode is `direct`. In a forward
// context alpaca talks to the corporate proxy, which does its own filtering,
// and putting a second filter in front of it would only add a hop.
//
// alpaca has no "always use this upstream" flag - a PAC file is its only way
// of naming one - so enabling this means generating a PAC and starting alpaca
// with `-C file://<it>`. macswitcher generates that file rather than pointing
// at a hand-written one: the local-network exceptions in it have to agree
// with local_proxy.no_proxy, and two hand-maintained copies of the same list
// disagree eventually.

// filterProxyStatePath is where the generated PAC is written: state, not
// configuration - it is derived from the config on every switch and is safe
// to delete.
func filterProxyPACPath(cfg Config) (string, error) {
	home, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	if custom := strings.TrimSpace(cfg.FilterProxy.PACFile); custom != "" {
		if strings.HasPrefix(custom, "~/") {
			return filepath.Join(home, custom[2:]), nil
		}
		return custom, nil
	}
	return filepath.Join(home, ".local", "state", "macswitcher", "filter.pac"), nil
}

// filterProxyAddr is the host:port alpaca is told to forward to.
func filterProxyAddr(cfg Config) string {
	host := strings.TrimSpace(cfg.FilterProxy.Host)
	if host == "" {
		host = "127.0.0.1"
	}
	port := cfg.FilterProxy.Port
	if port == 0 {
		port = defaultFilterProxyPort
	}
	return net.JoinHostPort(host, strconv.Itoa(port))
}

// filterProxyAppliesTo reports whether the filter belongs in the path for
// this context: enabled, and the context reaches the internet itself.
func filterProxyAppliesTo(cfg Config, ctx SwitchContext) bool {
	if !cfg.FilterProxy.Enabled {
		return false
	}
	return strings.EqualFold(strings.TrimSpace(ctx.ProxyMode), ProxyModeDirect)
}

// filterProxyListening probes the port rather than trusting launchd's idea of
// the job. A filter that is "running" but not accepting connections is the
// case the fail-open PAC quietly papers over, so it is the one worth
// answering directly.
func filterProxyListening(cfg Config) bool {
	ctx, cancel := context.WithTimeout(context.Background(), 400*time.Millisecond)
	defer cancel()
	var d net.Dialer
	conn, err := d.DialContext(ctx, "tcp", filterProxyAddr(cfg))
	if err != nil {
		return false
	}
	_ = conn.Close()
	return true
}

// filterProxyDirectHosts is what the PAC sends straight out, bypassing the
// filter: the machine's own no_proxy list plus anything named explicitly
// under filter_proxy.direct. Deduplicated and sorted so the generated file
// only changes when the inputs do.
func filterProxyDirectHosts(cfg Config) []string {
	seen := map[string]bool{}
	out := make([]string, 0, len(cfg.LocalProxy.NoProxy)+len(cfg.FilterProxy.Direct))
	for _, list := range [][]string{cfg.LocalProxy.NoProxy, cfg.FilterProxy.Direct} {
		for _, entry := range list {
			entry = strings.TrimSpace(entry)
			// Literal loopback and IPv6 loopback are handled numerically in
			// the generated PAC; carrying them here too would only produce
			// two rules that say the same thing.
			if entry == "" || entry == loopbackLocal || entry == loopbackIPv6 || seen[entry] {
				continue
			}
			seen[entry] = true
			out = append(out, entry)
		}
	}
	sort.Strings(out)
	return out
}

// renderFilterPAC builds the PAC alpaca is started with.
//
// Two properties worth keeping when editing this:
//
//   - No branch calls dnsResolve(). Every test is a string or arithmetic test
//     on the host, so evaluating the PAC never costs a DNS lookup - which
//     would otherwise happen on every request, through the resolver this same
//     tool reconfigures.
//   - IPv4 literals are compared numerically. Writing the private ranges as
//     shell globs is how 100.128.0.0/9 (public) ends up treated as Tailscale's
//     100.64.0.0/10, and how 172.32.x quietly joins RFC1918.
func renderFilterPAC(cfg Config) string {
	var b strings.Builder
	b.WriteString("// Generated by macswitcher - do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// Rewritten on every context switch from filter_proxy and\n")
	b.WriteString("// local_proxy.no_proxy in ~/.config/macswitcher/config.yaml.\n")
	b.WriteString("//\n")
	if cfg.FilterProxy.FailOpen {
		b.WriteString("// Fail-open: the trailing DIRECT means that if the filter is not\n")
		b.WriteString("// listening, alpaca connects directly and browsing continues\n")
		b.WriteString("// unfiltered. `macswitcher status` reports when that is the case.\n")
	} else {
		b.WriteString("// Fail-closed: no DIRECT fallback. If the filter is not listening,\n")
		b.WriteString("// requests fail rather than escaping unfiltered.\n")
	}
	b.WriteString("\nfunction FindProxyForURL(url, host) {\n")
	b.WriteString("    if (isPlainHostName(host)) {\n        return \"DIRECT\";\n    }\n\n")

	if hosts := filterProxyDirectHosts(cfg); len(hosts) > 0 {
		b.WriteString("    // local_proxy.no_proxy + filter_proxy.direct\n")
		b.WriteString("    if (")
		for i, h := range hosts {
			if i > 0 {
				b.WriteString(" ||\n        ")
			}
			// A leading dot means "and its subdomains"; anything else has to
			// match the host itself as well as below it.
			pattern := h
			if !strings.HasPrefix(pattern, ".") {
				fmt.Fprintf(&b, "host === %q || ", pattern)
				pattern = "." + pattern
			}
			fmt.Fprintf(&b, "dnsDomainIs(host, %q)", pattern)
		}
		b.WriteString(") {\n        return \"DIRECT\";\n    }\n\n")
	}

	b.WriteString(`    // mDNS/Bonjour.
    if (shExpMatch(host, "*.local")) {
        return "DIRECT";
    }

    // IPv4 literals, compared numerically - see the note above renderFilterPAC.
    var v4 = /^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$/.exec(host);
    if (v4) {
        var a = parseInt(v4[1], 10), b = parseInt(v4[2], 10);
        if (a === 127) return "DIRECT";                        // loopback
        if (a === 10) return "DIRECT";                          // RFC1918
        if (a === 192 && b === 168) return "DIRECT";            // RFC1918
        if (a === 172 && b >= 16 && b <= 31) return "DIRECT";   // RFC1918
        if (a === 169 && b === 254) return "DIRECT";            // link-local
        if (a === 100 && b >= 64 && b <= 127) return "DIRECT";  // CGNAT
    }

    // IPv6 loopback and unique-local.
    if (host === "::1" || shExpMatch(host, "fd*:*")) {
        return "DIRECT";
    }

`)
	if cfg.FilterProxy.FailOpen {
		fmt.Fprintf(&b, "    return \"PROXY %s; DIRECT\";\n}\n", filterProxyAddr(cfg))
	} else {
		fmt.Fprintf(&b, "    return \"PROXY %s\";\n}\n", filterProxyAddr(cfg))
	}
	return b.String()
}

// writeFilterPAC renders the PAC and puts it where alpaca can read it,
// returning the path. Written through a temporary file in the same directory
// and renamed, so alpaca - which may be reading it at this moment - never
// sees a half-written PAC.
func writeFilterPAC(cfg Config) (string, error) {
	path, err := filterProxyPACPath(cfg)
	if err != nil {
		return "", err
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return "", err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".filter-*.pac")
	if err != nil {
		return "", err
	}
	tmpName := tmp.Name()
	defer func() { _ = os.Remove(tmpName) }()
	if _, err := tmp.WriteString(renderFilterPAC(cfg)); err != nil {
		_ = tmp.Close()
		return "", err
	}
	if err := tmp.Close(); err != nil {
		return "", err
	}
	if err := os.Chmod(tmpName, 0o644); err != nil { // #nosec G302 -- alpaca reads it; it contains no secrets
		return "", err
	}
	if err := os.Rename(tmpName, path); err != nil {
		return "", err
	}
	return path, nil
}

// filterStatusDisabled is what status prints when the block is off - named
// so the test can assert on the same value rather than a second copy of it.
const filterStatusDisabled = "disabled"

// filterProxyStatusLine is the one-line summary `macswitcher status` prints.
//
// It exists because the fail-open PAC is silent by design: when the filter is
// down, alpaca connects directly and everything looks normal. This is the
// place that says otherwise, so it deliberately probes the port rather than
// reporting what the configuration intends.
func filterProxyStatusLine(cfg Config, ctx SwitchContext) string {
	if !cfg.FilterProxy.Enabled {
		return filterStatusDisabled
	}
	addr := filterProxyAddr(cfg)
	if !filterProxyAppliesTo(cfg, ctx) {
		return fmt.Sprintf("%s configured, not in path (proxy_mode=%s)", addr, ctx.ProxyMode)
	}
	if filterProxyListening(cfg) {
		return addr + ", in path, listening"
	}
	if cfg.FilterProxy.FailOpen {
		return addr + " NOT LISTENING - traffic is going out unfiltered (fail_open)"
	}
	return addr + " NOT LISTENING - requests will fail (fail_open: false)"
}

// privoxyDetail is the observe row's detail. Same reasoning as the status
// line: launchd's opinion of the job is already shown by the row itself, so
// what this adds is whether the port answers and whether this context sends
// anything through it at all.
func privoxyDetail(cfg Config) []string {
	if !cfg.FilterProxy.Enabled {
		return []string{"filter_proxy.enabled is false - not in any context's path"}
	}
	ctx, ok := cfg.Contexts[cfg.CurrentContext]
	if !ok {
		return []string{fmt.Sprintf("current context %q not found", cfg.CurrentContext)}
	}
	addr := filterProxyAddr(cfg)
	lines := []string{}
	if filterProxyListening(cfg) {
		lines = append(lines, "listening on "+addr)
	} else {
		lines = append(lines, "NOT listening on "+addr)
	}
	if filterProxyAppliesTo(cfg, ctx) {
		if path, err := filterProxyPACPath(cfg); err == nil {
			lines = append(lines, fmt.Sprintf("in path for %q via %s", cfg.CurrentContext, path))
		}
		if !filterProxyListening(cfg) && cfg.FilterProxy.FailOpen {
			lines = append(lines, "fail_open: traffic is leaving unfiltered right now")
		}
	} else {
		lines = append(lines, fmt.Sprintf("not in path: context %q is proxy_mode=%s",
			cfg.CurrentContext, ctx.ProxyMode))
	}
	return lines
}

// commandNamesPAC reports whether an alpaca command line names a PAC file
// itself. Deliberately an exact match on the flag rather than a substring
// test: commandUsesToken looks for "-C" anywhere in any argument, which a
// file path is free to contain.
func commandNamesPAC(parts []string) bool {
	for _, part := range parts {
		if part == "-C" || strings.HasPrefix(part, "-C=") {
			return true
		}
	}
	return false
}
