package app

import (
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"
)

func TestDscacheutilOutputHasAddress(t *testing.T) {
	t.Parallel()

	tests := []struct {
		name string
		out  string
		want bool
	}{
		{
			name: "ipv4 address present",
			out:  "name: google.com\nip_address: 142.251.110.113\n",
			want: true,
		},
		{
			name: "ipv6 address present",
			out:  "name: google.com\nipv6_address: 2a00:1450:4001:c15::8b\n",
			want: true,
		},
		{
			name: "no address (unresolvable host)",
			out:  "",
			want: false,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			if got := dscacheutilOutputHasAddress(tt.out); got != tt.want {
				t.Fatalf("dscacheutilOutputHasAddress(%q) = %v, want %v", tt.out, got, tt.want)
			}
		})
	}
}

func TestCheckDNSResolutionForwardModeRequiresProxyServer(t *testing.T) {
	t.Parallel()

	ctx := SwitchContext{
		ProxyMode:      ProxyModeForward,
		ForwarderProxy: &ForwarderProxyConfig{},
	}
	err := checkDNSResolution(ctx)
	if err == nil {
		t.Fatal("expected an error when forward mode has no proxy_server configured")
	}
}

// The per-domain "[/zone/]addr" upstreams in AdGuard Home's upstream file come
// from unbound's forward-zones (the work overlay's intranet zones), not from
// macswitcher. A context switch rewrites the default upstreams and must carry
// those over untouched - losing them takes the intranet off the air in a way
// that only shows up on the next intranet lookup.
func TestWriteAdGuardUpstreamsPreservesPerDomainEntries(t *testing.T) {
	t.Parallel()

	path := filepath.Join(t.TempDir(), "upstreams.conf")
	existing := strings.Join([]string{
		"# Generated by unbound_to_adguard.py",
		"9.9.9.9",
		"8.8.8.8",
		"",
		"# from corp.conf",
		"[/corp.example/]10.0.0.106",
		"[/intranet.example/]10.0.0.107",
		"",
	}, "\n")
	if err := os.WriteFile(path, []byte(existing), 0o644); err != nil {
		t.Fatalf("seed upstreams: %v", err)
	}

	cfg := Config{AdGuard: AdGuardConfig{UpstreamsFile: path}}
	if err := writeAdGuardUpstreams(cfg, []string{"10.0.0.149", " ", "10.0.0.70"}, "work"); err != nil {
		t.Fatalf("writeAdGuardUpstreams() error = %v", err)
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read back: %v", err)
	}
	defaults, specific, err := currentAdGuardUpstreams(path)
	if err != nil {
		t.Fatalf("currentAdGuardUpstreams() error = %v", err)
	}

	if want := []string{"10.0.0.149", "10.0.0.70"}; !slices.Equal(defaults, want) {
		t.Errorf("defaults = %v, want %v", defaults, want)
	}
	if want := []string{"[/corp.example/]10.0.0.106", "[/intranet.example/]10.0.0.107"}; !slices.Equal(specific, want) {
		t.Errorf("per-domain = %v, want %v", specific, want)
	}
	// The previous network's resolvers must be gone, not merely appended to.
	if strings.Contains(string(got), "9.9.9.9") {
		t.Errorf("stale default upstream 9.9.9.9 survived the rewrite:\n%s", got)
	}
	// AdGuard Home rejects a line with a trailing comment, so every comment
	// has to sit on a line of its own.
	for _, line := range strings.Split(string(got), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		if strings.Contains(line, "#") {
			t.Errorf("upstream line carries a trailing comment, which AdGuard Home rejects: %q", line)
		}
	}
}

// An empty upstreams_file means the machine has not opted into the trial.
func TestWriteAdGuardUpstreamsRequiresConfiguredPath(t *testing.T) {
	t.Parallel()

	if err := writeAdGuardUpstreams(Config{}, []string{"9.9.9.9"}, "home"); err == nil {
		t.Fatal("expected an error when adguard.upstreams_file is empty")
	}
}
